function [modelswp, model] = SaveModel(swp,model,Cpg,Lg,Rg,Cgs,Ri,Cgd,Rj,Rds,Cds,Rd,Cpd,Ld,Rs,Ls,gm,tau_gm)
model_params = [Cpg/2,Lg,Rg,Cgs,Ri,Cgd,Rj,Rds,Cds,Rd,Cpd/2,Ld,Rs,Ls,gm,tau_gm];
[model xp_model] = reduce(model,model_params); % creats the two ports parameter of the model(S,Y,Z...)
temp = swp; % Copy the swp
temp.data =  xp_model.S; %Replace/switch the data
modelswp = temp;
mstate = get(modelswp,'measstate');
mstate = addprop(mstate,'Cpg',Cpg);
mstate = addprop(mstate,'Rg',Rg);
mstate = addprop(mstate,'Lg',Lg);
mstate = addprop(mstate,'Rs',Rs);
mstate = addprop(mstate,'Rd',Rd);
mstate = addprop(mstate,'Ld',Ld);
mstate = addprop(mstate,'Cpd',Cpd);
mstate = addprop(mstate,'Cgs',Cgs);
mstate = addprop(mstate,'Cgd',Cgd);
mstate = addprop(mstate,'Rds',Rds);
mstate = addprop(mstate,'gds',1/Rds);
mstate = addprop(mstate,'Cds',Cds);
mstate = addprop(mstate,'gm',gm);
mstate = addprop(mstate,'tau_gm',tau_gm);
mstate = addprop(mstate,'Ri',Ri);
mstate = addprop(mstate,'Rj',Rj);
modelswp = set(modelswp,'measstate',mstate);